### ISSUE TITLE
Error copying file "gle.cpp" to "gle_cpp_lib.cpp".

### ISSUE THREAD

**Issue by ryandesign** [vlabella/GLE#26]
While working on setting up GitHub Actions CI for GLE (#25) I found this build failure:

```
gmake[2]: Entering directory '/home/runner/work/GLE/GLE/build'
gmake[2]: Entering directory '/home/runner/work/GLE/GLE/build'
[ 30%] Generating gle_cpp_lib.cpp from gle.cpp
[ 31%] Generating gle_cpp_lib.cpp from gle.cpp
cd /home/runner/work/GLE/GLE/src/gle && /usr/local/bin/cmake -E copy gle.cpp gle_cpp_lib.cpp
gmake[2]: Leaving directory '/home/runner/work/GLE/GLE/build'
cd /home/runner/work/GLE/GLE/src/gle && /usr/local/bin/cmake -E copy gle.cpp gle_cpp_lib.cpp
/usr/bin/gmake  -f gle/CMakeFiles/gle.dir/build.make gle/CMakeFiles/gle.dir/build
Error copying file "gle.cpp" to "gle_cpp_lib.cpp".
gmake[2]: Entering directory '/home/runner/work/GLE/GLE/build'
gmake[2]: *** [gle/CMakeFiles/libgle-graphics_s.dir/build.make:74: /home/runner/work/GLE/GLE/src/gle/gle_cpp_lib.cpp] Error 1
gmake[2]: Leaving directory '/home/runner/work/GLE/GLE/build'
cd /home/runner/work/GLE/GLE/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/runner/work/GLE/GLE/src /home/runner/work/GLE/GLE/src/gle /home/runner/work/GLE/GLE/build /home/runner/work/GLE/GLE/build/gle /home/runner/work/GLE/GLE/build/gle/CMakeFiles/libgle-graphics.dir/DependInfo.cmake "--color="
gmake[2]: *** Deleting file '/home/runner/work/GLE/GLE/src/gle/gle_cpp_lib.cpp'
gmake[1]: *** [CMakeFiles/Makefile2:270: gle/CMakeFiles/libgle-graphics_s.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

I am doing a parallel build with `-j4`.

It's trying to generate gle_cpp_lib.cpp from gle.cpp twice at the same time—likely once for the static library and once for the shared library—and one of them fails.

https://github.com/vlabella/GLE/blob/97cf2ca024ef9a12abf6fe6024439faf0c82a0e8/src/gle/CMakeLists.txt#L100-L101

This suggests dependencies aren't declared properly. I think this may be because you've only used `add_custom_command` but haven't used `add_custom_target` and then used that target as a dependency of whatever needs it.

https://github.com/vlabella/GLE/blob/97cf2ca024ef9a12abf6fe6024439faf0c82a0e8/src/gle/CMakeLists.txt#L81-L87

**Comment by ryandesign** [comment]
Why is gle_cpp_lib.cpp needed at all? It says "Generating gle_cpp_lib.cpp from gle.cpp" but all it does is copy the file; after being "generated" from gle.cpp, gle_cpp_lib.cpp is identical to gle.cpp.

**Comment by vlabella** [comment]
Its needed to build the gle C++ library.  It gets compiled with the HAVE_LIBGLE flag set.  gle.cpp is compiled with that flag off for the executable.    A simple solution was to copy it to a different name and compile that file for the library. If there is a way in cmake to compile gle.cpp twice with and without the flag then there is no need to copy it.

**Comment by ryandesign** [comment]
Ok, yes there seems to be a way in cmake to build a single source file multiple times with different flags, so then you won't need to copy the file and the parallel build problems associated with that should go away. I'll try to change this soon.

**Comment by vlabella** [comment]
thanks
