### ISSUE TITLE
Policy CMP0167 is not set: The FindBoost module is removed.

### ISSUE THREAD

**Issue by ryandesign** [vlabella/GLE#27]
This message appears while building GLE 4.3.4:

```
CMake Warning (dev) at CMakeLists.txt:118 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

See https://cmake.org/cmake/help/latest/policy/CMP0167.html

**Comment by ryandesign** [comment]
Using the new behavior of CMP0167 would mean requiring cmake 3.30 which was just released one month ago today. That would be a problem for the many Linux distributions that update their packages more conservatively and haven't updated to that version of cmake yet.

Probably better to keep using the old behavior of the policy, adding it explicitly in CMakeLists.txt to silence the warning, with a comment to reevaluate it some years down the road when availability of cmake ≥ 3.30 is more commonplace.

**Comment by vlabella** [comment]
the CMP0167 policy has been commented out and will be turned on at a later date.
